[package]
name = "texture-atlas"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
image = { workspace = true, optional = true }
imageproc = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
thiserror = { workspace = true }

[features]
default = [
	"image",
	"packer-binary",
	"packer-passthrough",
	"packer-uniform",
	"serde",
]
image = ["dep:image", "dep:imageproc"]
packer-binary = []
packer-passthrough = []
packer-uniform = []
serde = ["dep:serde"]
